# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95d010d944ddcc69b27137109d59b785dd06aa0e04caf9dd14d1a5e24fb62491b4603825424ed5b9df671ae03fe01c02921c4a14dbb50c7b6b1d9280c602c022

test:
  secret_key_base: 7bc579a85ce011caec6eae8262fd197dbbca57534f66390ea9b913f8969c441c511f2474d24055419d5d1216323bf9a4eb32ef5ad2dfef0db3cde81eb6f84314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
